#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache # add this line to the plugins list if you already have one
  - jekyll-paginate


title: JEKYLL WEBPAGE

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  recipes:
    output: true
    permalink: /recipes/:path/



# número de posts por página
paginate: 5
paginate_path: /blog/page:num/



minima:
  skin: neon

name: peter
  