markdown: kramdown
remote_theme: jekyll-theme-leaf


plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache # add this line to the plugins list if you already have one
  - jekyll-paginate

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site



title: Isra blog

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  recipes:
    output: true
    permalink: /recipes/:path/



# número de posts por página
paginate: 5
paginate_path: /blog/page:num/




name: isra @copryright reserved 2023
  